server:
  port: 2245

spring:
  application:
    name: MUZIX-MANAGER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defuaultZone: http://localhost:8761/eureka/  
     instance:  
         hostname: localhost
         